name: CI Build and Test (Local setup)

on: [push, pull_request]
  
env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] #, ubuntu-latest]
        include: 
          # - os: ubuntu-latest
          #   file_suffix: "-linux"
          - os: macos-latest
            file_suffix: "-mac"
     
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up environment
      run: |
        echo "Setting up on ${{ matrix.os }}"
        mv ic-test-machine-binaries/ic-test-state-machine${{ matrix.file_suffix }} ic-test-state-machine
    - name: Install dfx  
      uses: dfinity/setup-dfx@main
    - name: Confirm successful installation
      run: dfx --version
    - name: Install Rust target
      run: rustup target add wasm32-unknown-unknown
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3
    - name: Install dependencies
      run: |
        npm install 
        cargo install ic-wasm
    # - name: Run the deploy script to deploy all the canisters to local environment
    #   run: |
    #     export VITE_ENV="development"
    #     ./scripts/deploy-civic.sh
    - name: Run tests
      run: |
        chmod +x ic-test-state-machine
        cargo test --test integration_tests
