name: CI Build and Test (Local setup)

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        include: 
          - os: ubuntu-latest
            file_suffix: "-linux"
     
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        echo "Setting up on ${{ matrix.os }}"
        mv ic-test-machine-binaries/ic-test-state-machine${{ matrix.file_suffix }} ic-test-state-machine

    - name: Install dfx  
      uses: dfinity/setup-dfx@main

    - name: Confirm successful installation
      run: dfx --version

    - name: Install Rust target
      run: rustup target add wasm32-unknown-unknown

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2.7.3
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm install

    - name: Install additional Cargo tools
      run: cargo install ic-wasm
    - name: Set and Export ENV
      run: echo "TARGET_ENV=ubuntu" >> $GITHUB_ENV

    - name: Print ENV
      run: echo $TARGET_ENV

    - name: Build project
      run: cargo build --target wasm32-unknown-unknown --release -vv
    - name: Run tests
      run: |
        chmod +x ic-test-state-machine
        cargo test -- --nocapture
