name: CI Build and Test

on: [push, pull_request]
  # push:
  #   branches: [ "gh-actions" ]
  # pull_request:
  #   branches: [ "gh-actions" ]


env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include: 
          - os: ubuntu-latest
            file_suffix: "-linux"
          - os: macos-latest
            file_suffix: "-mac"
     
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up environment
      run: |
        echo "Setting up on ${{ matrix.os }}"
        mv ic-test-machine-binaries/ic-test-state-machine${{ matrix.file_suffix }} ic-test-state-machine

    - name: Install dfx  
      uses: dfinity/setup-dfx@main
    - name: Confirm successful installation
      run: dfx --version
    - name: Install Rust target
      run: rustup target add wasm32-unknown-unknown
    - name: Install dependencies
      run: |
        npm install 
        cargo install ic-wasm
    - name: Install canisters and start local ICP replica
      run: |
        mkdir src/civic_canister_backend/dist
        dfx start --clean --background
        dfx canister create --all
    - name: Build canisters
      run: dfx build --verbose
    - name: Deploy canisters
      run: dfx canister install --all && dfx deploy 
    - name: Run tests
      run: |
        chmod +x ic-test-state-machine
        cargo test --test integration_tests --verbose
    - run: echo "🐧 This job's status is ${{ job.status }}."
